name: Publish (Launchpad)

on:
  push:
    tags: 'debian/*'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Upload to PPA
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: '${{ secrets.GPG_PRIVATE_KEY }}'
          passphrase: '${{ secrets.GPG_PASSPHRASE }}'
      - name: Install dependencies
        run: cd debian && sudo make deps
      - name: Create cowbuilder image
        run: cd debian && sudo make dist/create
      - name: Build binary package
        run: cd debian && make dist
      - name: Build source package
        run: cd debian && make clean && make src
      - name: Upload to PPA
        run: cd debian && make upload
